### ISSUE TITLE
get BSSID of Access point?

### ISSUE THREAD

**Issue by kkar** [DigiExam/simplewifi#19]
It seems that i cannot find a way to get the BSSID (Mac address) of the access points. I can get only the name and signal instead. Is there a way to get the access point's bssid?

Thanks.

**Comment by yatt-ze** [comment]
Although not using simple wifi, you can using managed wifi:   
```
var wlanClient = new WlanClient();
foreach (WlanClient.WlanInterface wlanInterface in wlanClient.Interfaces)
{
	Wlan.WlanBssEntry[] wlanBssEntries = wlanInterface.GetNetworkBssList();
	foreach (Wlan.WlanBssEntry wlanBssEntry in wlanBssEntries)
	{
		byte[] macAddr = wlanBssEntry.dot11Bssid;
		Wlan.Dot11Ssid ssid = wlanBssEntry.dot11Ssid;
		string networkName = Encoding.ASCII.GetString(ssid.SSID, 0, (int)ssid.SSIDLength);
		var macAddrLen = (uint)macAddr.Length;
		var str = new string[(int)macAddrLen];
		for (int i = 0; i < macAddrLen; i++)
		{
			str[i] = macAddr[i].ToString("x2");
		}
		string mac = string.Join(":", str);
		console.writeline(networkName +  " --> " + mac.ToUpper());
	}
}
```

**Comment by sajjadjaved01** [comment]
not working for me ..

**Comment by yatt-ze** [comment]
1) Did you read the whole question or just copy the code?  
2) What part of the code doesn't work?
Etc, etc  

Just saying "not working" doesn't help anyone

**Comment by kkar** [comment]
Well, that worked for me as expected. Copy paste won't help though.

**Comment by sajjadjaved01** [comment]
i have tried ... but unable to resolve WlanInterface
