### ISSUE TITLE
Feature request: Add Scan() function to Wifi class

### ISSUE THREAD

**Issue by flyingxu** [DigiExam/simplewifi#29]
During my test, some wifi SSID will disappear intermittently but then they appear again if I click on the WiFi icon in the Windows status tray. Sometimes I need to click the WiFi icon several times to see the specific SSID.  

I think a re-scan begins each time I click the WiFi icon, seem to be this [`WlanScan `](https://msdn.microsoft.com/en-us/library/windows/desktop/ms706783(v=vs.85).aspx) function. In the interop code, it seems to be the [`Scan`](https://github.com/DigiExam/simplewifi/blob/master/SimpleWifi/Win32/WlanInterface.cs#L235) function.

I think it will be useful if we expose this 'Scan' function to 'Wifi' class, so we can call like this:

```
    var wifi = new Wifi();
    wifi.Scan();  //the feature request
    var apList = wifi.GetAccessPoints();
```

By the additional call of `Scan()`, we can try till we get the specific AP.

Is it possible?

Thanks.

**Comment by yatt-ze** [comment]
So are you trying to "refresh" your list of ssids?

**Comment by flyingxu** [comment]
Yes. When a new WiFi AP is on, the list of ssids will not update until the WiFi tray icon is clicked and the WiFi list is re-displayed by Windows. 
Actually it's not that hard, if you think it can be merged into SimpleWiFi, I can create a PR.

**Comment by yatt-ze** [comment]
Can't you write a function to clear then refresh the list, and then put it on a clock / diffrent thread? it's what i did in my project

**Comment by flyingxu** [comment]
Yes I agree.
