### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by mongeon** [DigiExam/simplewifi#6]
Creating a nuget package could provide more visibility to the project and allow users to keep their package up-to-date with new release.

**Comment by luugiathuy** [comment]
:+1: for this feature

**Comment by JohnHardy** [comment]
A nuget package would be great :+1:

**Comment by robinwassen** [comment]
Guess later is better than never, SimpleWifi is now available as NuGet package: https://www.nuget.org/packages/SimpleWifi
